let passwords = [
    {
        id:1,
        username:"nurillo",
        password:"123"
    },
    {
        id:2,
        username:"ulug'bek",
        password:"123"
    },
    {
        id:3,
        username:"shamsiddin",
        password:"123"
    },
    {
        id:4,
        username:"mirzo",
        password:"123"
    },
    {
        id:5,
        username:"sarvar",
        password:"123"
    },
    {
        id:6,
        username:"ozodbek",
        password:"123"
    },
    {
        id:7,
        username:"nigora",
        password:"123"
    },
    {
        id:8,
        username:"laylo",
        password:"123"
    },
    {
        id:9,
        username:"muslima",
        password:"123"
    },
    {
        id:10,
        username:"dilnoza",
        password:"123"
    },
    {
        id:11,
        username:"roziya",
        password:"123"
    },
    {
        id:12,
        username:"hamroz",
        password:"123"
    },
    {
        id:13,
        username:"ibrohim",
        password:"123"
    },
    {
        id:14,
        username:"abduvohob",
        password:"123"
    },
    {
        id:15,
        username:"abdulla",
        password:"123"
    },
    {
        id:16,
        username:"muhammadali",
        password:"123"
    }
]